### ISSUE TITLE
lbdbq says no matches...

### ISSUE THREAD

**Issue by sequethin** [tgray/lbdb#2]
I've got a lot of contacts in the address book on my mac, was expecting lbdbq to return a lot of info if I didn't query something specific. Instead all I can seem to get is "no matches." I can't seem to get any results back no matter what I do. What am I doing wrong?

**Comment by tgray** [comment]
Sorry for not getting back to you sooner.  Frankly, I don't know what's wrong.  I began working on a light weight replacement to lbdb (for OS X) and noticed that the Address Book tool included in lbdb doesn't work the way it should.  Frankly I forget the details but I'm not sure if it's worth fixing them because my replacement fixes that and does the other things I need it to (search mutt alias files and a sent address database).  I'll try to post it shortly.

**Comment by tgray** [comment]
Update.  I just merged a pull request, and noticed while I was working on it, lbdb had stopped searching my Address Book as well.  I updated a setting in the Xcode project and all seems to be working again here.  So hopefully the newest commit will work for you.
